
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-naglfar-pingcap-com-v1-machine
  failurePolicy: Fail
  name: mmachine.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-machine
  failurePolicy: Fail
  name: vmachine.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
