# permissions for end users to edit machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-editor-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - machines/status
  verbs:
  - get
