# permissions for end users to edit testresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testresource-editor-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresources/status
  verbs:
  - get
