# permissions for end users to view testresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testresource-viewer-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresources/status
  verbs:
  - get
